name: repatriationapp
description: "A Flutter application for repatriation services."
publish_to: 'none' # Remove for public packages

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # UI & Design
  bubble: ^1.2.1
  dropdown_search: ^5.0.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.1.0
  pinput: ^5.0.1

  # Firebase
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.3.0

  # Network & APIs
  connectivity_plus: ^6.1.4
  http: ^1.3.0

  # Location Services
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.1

  # Media Handling
  image: ^4.5.4
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.20.2
  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    # Fonts
    - assets/fonts/Manrope-Bold.ttf
    - assets/fonts/Manrope-ExtraBold.ttf
    - assets/fonts/Manrope-ExtraLight.ttf
    - assets/fonts/Manrope-Light.ttf
    - assets/fonts/Manrope-Medium.ttf
    - assets/fonts/Manrope-Regular.ttf
    - assets/fonts/Manrope-SemiBold.ttf
    - assets/fonts/Manrope-VariableFont_wght.ttf
    - assets/fonts/OFL.txt
    - assets/fonts/README.txt

    # Icons
    - assets/google_icon.png
    - assets/icons/donee.png
    - assets/icons/donor.png
    - assets/icons/volunteer.png
    - assets/icpc_logo.png

    # Images
    - assets/images/syrian_flag.png
    - assets/onboarding_image_1.png
    - assets/onboarding_image_2.png
    - assets/onboarding_image_3.png

    # SVGs
    - assets/onboarding1.svg
    - assets/onboarding2.svg